{% set version = "4.19.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-umx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/umx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/umx/umx_{{ version }}.tar.gz
  sha256: 45c3b76959efeabd090750dfe2a3b7c4b2a5c6f5ed27a9fb843b16019e40e432

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cowplot
    - r-diagrammer
    - r-foreign
    - r-gert
    - r-ggplot2
    - r-hrbrthemes
    - r-kableextra
    - r-knitr
    - r-lavaan
    - r-mass
    - r-matrix
    - r-mumin
    - r-mvtnorm
    - r-nlme
    - r-openmx >=2.19.0
    - r-openxlsx
    - r-paran
    - r-polycor
    - r-psych
    - r-psychtools
    - r-pwr
    - r-r2html
    - r-rcurl
    - r-rmarkdown
    - r-scales
    - r-xtable
  run:
    - r-base
    - r-cowplot
    - r-diagrammer
    - r-foreign
    - r-gert
    - r-ggplot2
    - r-hrbrthemes
    - r-kableextra
    - r-knitr
    - r-lavaan
    - r-mass
    - r-matrix
    - r-mumin
    - r-mvtnorm
    - r-nlme
    - r-openmx >=2.19.0
    - r-openxlsx
    - r-paran
    - r-polycor
    - r-psych
    - r-psychtools
    - r-pwr
    - r-r2html
    - r-rcurl
    - r-rmarkdown
    - r-scales
    - r-xtable

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('umx')"                                                          # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('umx')\""                                                 # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/tbates/umx
  license: GPL-3.0-only
  summary: Quickly create, run, and report structural equation and twin models. See '?umx' for help, and umx_open_CRAN_page("umx") for NEWS.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann
