{% set version = "4.16.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-umx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/umx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/umx/umx_{{ version }}.tar.gz
  sha256: b3dfabf87dfa5c8c06960d76659ad3ba6290bb54b1152554157d389b18ab7212

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-diagrammer
    - r-diagrammersvg
    - r-mass
    - r-matrix
    - r-mumin
    - r-openmx >=2.19.0
    - r-r2html
    - r-rcurl
    - r-cowplot
    - r-ggplot2
    - r-kableextra
    - r-knitr
    - r-lavaan
    - r-mvtnorm
    - r-nlme
    - r-polycor
    - r-rsvg
    - r-scales
    - r-xtable
  run:
    - r-base
    - r-diagrammer
    - r-diagrammersvg
    - r-mass
    - r-matrix
    - r-mumin
    - r-openmx >=2.19.0
    - r-r2html
    - r-rcurl
    - r-cowplot
    - r-ggplot2
    - r-kableextra
    - r-knitr
    - r-lavaan
    - r-mvtnorm
    - r-nlme
    - r-polycor
    - r-rsvg
    - r-scales
    - r-xtable

test:
  commands:
    - $R -e "library('umx')"           # [not win]
    - "\"%R%\" -e \"library('umx')\""  # [win]

about:
  home: https://github.com/tbates/umx
  license: GPL-3.0-only
  summary: Quickly create, run, and report structural equation and twin models. See '?umx' for help, and umx_open_CRAN_page("umx") for NEWS.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann
